name: eda_projects             # Name of the environment
channels:
  - defaults               # Default Conda channel
  - conda-forge            # Optional: additional channel for some packages
dependencies:
  - python=3.11            # Python version
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - plotly
  - jupyter
  - notebook
  - ipykernel
  - scikit-learn
  - pyyaml
  - pip                     # pip is required if you want to install pip-only packages
  - pip:
      - ydata-profiling     # Install via pip because Pandas Profiling may not be on Conda
      - dvc                 # DVC latest version via pip
